- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/AgreeTerms/VC/AgreeTermsVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpMajorInfoVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/VC/SignUpUserInfoVC.swift
closed #29 
* 회원가입 과정의 모든 엑스(X) 버튼에서 Alert View가 나오도록 하여 화면 전환 적용
* 근데 이 Alert 나오게 하는 메소드 언젠가 BaseVC에 추가할까봐여
은근 귀찮네
https://user-images.githubusercontent.com/43312096/149086808-53021e66-b8b1-4f82-93ab-95974c092028.MP4
> ✨ [FEAT] 회원가입 - 종료 시 alert 띄우기

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UITextView+.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/Identifiers.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoSunbaeNaviBar.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/SB/WriteQuestionSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift
closed #44 
- UITextView+에 lineCount를 return 하는 메서드를 추가했습니다!
- NadoSunbaeNaviBar에서 백그라운드 컬러가 투명하다는 민원을 받아 백그라운드뷰를 추가해두었습니다 ~~ 이제 백뷰 안만드셔도 돼 선배들,,
- 과방탭 textView height가 굉장히 커서.. 키보드 액션땜에 고민을 마니 했는데..!
- 매끄러운 스크롤을 위해서 하단에 스크롤뷰를 깔아 구현해봤음 ~~
- 글고 재사용선배 진짜 짱조아.. 
- 시뮬 구동 영상
- 키보드 나올 때 구동 영상
> ✨ [FEAT] 과방탭 - 질문 작성뷰 UI 구현

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/String+.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/Cell/MypageQuestionTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/Cell/NotificationTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC.swift
closed #70 
* String+ `serverTimeToString()` 추가
* String+ `toDate()` 추가
* 마이페이지, 선배페이지, 알림탭에서 시간 처리 적용
* String+ `serverTimeToString()` 사용법
`timeLabel.text = data.writeTime.serverTimeToString(forUse: .forDefault)`
위와 같이 사용하심 됩니다~! 대신 `data.writeTime`은 `String` 타입, `"2021-11-28T18:56:42.040Z"` 의 형태로 들어가 있어야 함!! API docs 보니까 서버에서 시간을 저 형태로 주더라구여~
`.forDefault`: 알림 탭 제외 모두, 19/12/11의 형태로 반환
`.forNotification`: 알림 탭에서 요구하는 형태로 반환
* String+ 의 `toDate()` 함수는 UI 내에서 쓸 일 없어 보여서 private 처리해 놨는데... 혹시 써야 한다면 private 빼면 됩니다...!
```
private func toDate() -> Date {
}
```
> ✅ [CHORE] 시간 처리 함수 추가

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
closed #78
- 위로 스크롤시 bounce 효과처럼 scroll이 되어서 배경 이미지 뒤의 화면이 보이는 문제가 있었습니다.
- 컨텐츠가 화면 상단에 닿을 시 스크롤이 안되게 하여 배경 이미지가 고정되도록 기능을 수정하였습니다.
> ✅ [CHORE] Contents가 화면 상단에 닿았을 때 scroll disabled 되도록 수정

- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewPostDetailData.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostWithImgTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostWithImgTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainPostTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewWriteSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
closed #115
- 학과 리스트에서 학과 선택 시 후기 메인 뷰에 해당 학과의 후기글이 리스트업 되고, 
다른 탭으로 이동해도 해당학과로 진입하도록 하였습니다.
- 지은이의 코드를 쇽샥해서 해당학과 리스트가 뜨도록 서버 통신하였고, `UserDefaults`값과 싱글톤 객체를 이용해 선택된 학과가 저장되어 다른 탭에서도 반영이 되도록 했습니다.
- 배경 이미지 GET에서 계속 초기화 값으로만 들어온다는 문제가 있었는데, 값이 들어오도록 해결해서 게시글에 해당하는 배경 이미지가 뜨도록 했습니다.
- 후기 작성 뷰에서 이중전공이 없는 유저일 경우 변경 버튼이 비활성화 되고, 이중전공이 있는 유저일 경우 변경 버튼 클릭 시 `ActionSheet`에서 학과를 선택할 수 있도록 하였습니다.
- 자잘한 UI 수정이 있었습니다..
> ✨[FEAT] 학과 선택에 따라 게시글 리스트 바뀌도록 서버 통신 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
closed #161
- 후기글을 쓰지 않은 유저에 대해 게시글 열람을 제한하는 기능을 구현했습니다.
- `UserDefaults`의 `isReviewed`값을 이용해서 기능을 구현했습니다.
- 후기글 post시 기존 `UserDefaults`의 `isReviewed`값에 관계없이 `true`로 상태가 업데이트 되어야하기 때문에 post서버 통신 완료 시에 `true`값을 세팅해주었습니다. 
- 게시글 클릭시 `UserDefaults`에 저장된 값으로 분기처리하여 알럿을 띄웠습니다.
- 알럿 메시지 행간격은 다음 PR에 게시글 행간격 조정하며 함께 변경하도록 하겠습니다!
- 게시글 열람 제한
https://user-images.githubusercontent.com/63277563/153417648-f5b64f45-d684-44dc-9df0-529a23014f1d.mp4
- 후기 미작성자가 후기글 작성완료 시 권한 변경
https://user-images.githubusercontent.com/63277563/153417662-c60b9e42-824e-472f-84be-64e513c2612b.mp4
> ✨ [FEAT] 후기 미작성 유저 게시글 열람 제한 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UILabel+.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoAlertVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/NadoAlertVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostWithImgTVC.swift
closed #163
- NadoAlert, 후기상세 뷰의 행간격을 설정했습니다.
- `UILabel+` 파일의 `setLineSpacing(`)을 수정했습니다.
(수정이유: 이미 거의 모든 파일에서 Label의 폰트, 크기 등이 설정되어있기 때문에 `setLineSpacing(lineSpacing: )`으로 원하는 행간격 값만 설정해줄 수 있도록 수정, 반환값이 필요없을 것 같아서 return문 삭제)
- 정빈이가 만들어 놓은 NadoAlert()에 위의 함수를 호출해 알럿 메시지가 두 줄 이상이라면 모두 동일한 행간격이 적용되도록 했습니다. + 피그마보다가 `messageLabel`색상이 다르게 설정되어있어서 피그마와 동일하게 변경도 해놓았습니다.
- 후기 상세 뷰도 동일하게 행간격 설정했습니다.
- 비교 스크린샷
> ✅ [CHORE] Label 행간격 설정

- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewMainPostListData.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainLinkTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainPostTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
closed #169
- 후기 메인 뷰의 학과 홈페이지, 이수과목 일람표 버튼 클릭시, 
기존의 웹뷰 이동 방식에서 인앱 브라우저 연결 방식으로 변경하였습니다.
- `SafariServices`를 임포트하여 앱 안에서 해당 링크로 이동할 수 있도록 하였습니다.
(참고: 보라보라봉 티스토리💜)
- 데이터 전달은 클로저를 이용하였습니다.
- 구동영상(서버에서 DB수정중이라 학과 선택 시 '미진입'이 뜨는 것은 무시해주시면 될 것 같습니다!)
https://user-images.githubusercontent.com/63277563/153757737-b5cbfb91-3717-4bed-81d9-b811bc435bd6.mp4
> ✅ [CHORE] 후기 메인 뷰 URL 네이티브 앱 연결 형식으로 수정

- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewMainPostListData.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewPostDetailData.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainPostTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
closed #173 
- 서버 API 수정에 따라 후기 탭에 사용되는 모델과 네트워크 코드(변수명, 데이터타입)를 수정했습니다.
- 수정하면서 PostLike -> Like로 통일하였습니다.
지은걸 파일까지 수정완료 되면 PostLike 부분 삭제하겠습니다!
> 🔨 [FIX] 후기 탭 변수 데이터 타입 수정

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UserDefaults+.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Sign/SignInDataModel.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/SB/SignInSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Support/SceneDelegate.swift
closed #172
* 자동로그인 구현
~ 로직 설명 ~
* `SignInVC`에서 로그인 성공했을 경우 `UserDefaults`에 아이디/비번 저장
* `AutoSignInVC`에서 로그인 성공/실패 판단하여 후기탭으로 갈지 `SignInVC`로 갈지 분기 처리
* `AutoSignInVC`에서 로그인 실패한 경우(설치후 첫실행이라 데이터 없을 경우, 불의의 사고로 계정이 없거나 변경되었을 경우 등등...) 하나로 퉁쳐서 `switch-case`문 `default`로 처리!
* `AutoSignInVC` 뷰는 런치스크린 뷰랑 동일하게 구성! 이건 디자인쌤들이 나중에 런치스크린 완성해 주시면 이미지만 넣으면 됩니당~
* `SignUpVC`에서 회원가입 성공했을 경우 `UserDefaults`에 아이디/비번 저장 -> `SignInVC`로 이동하지 않고 바로 로그인 요청 .... ~회원가입마무리하고구현할게염~
직접확인해보세요. ㅋ 순식간에 지나가서 업슴
> ✨ [FEAT] 자동로그인 구현

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ReviewAPI.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewDeleteResModel.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewPostDetailData.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
closed #178 
- 후기글 삭제 기능을 구현 했습니다.
- 작성자 기준 수정,삭제/신고 분기처리 (`writerID`와 `userID` 비교)
- 삭제 버튼 클릭 시 나타나는 알럿 창 추가 및 DELETE 서버 통신
- 작성한 게시글 모두 삭제했다면 후기글 열람 다시 제한 
- `WriteVC` 완료 버튼 분기처리 코드 수정 
**이제 더미? 클라에서 관리해.**
- 작성자 기준 수정,삭제/신고 분기처리
- 후기글 삭제
https://user-images.githubusercontent.com/63277563/154417726-f1a4e567-4099-459b-8338-303f675f1cb7.mp4
- 내가 쓴 게시글 모두 지웠다면 열람 권한 뺏기
https://user-images.githubusercontent.com/63277563/154417922-70d3434a-74e3-4ed8-a0bc-8150ea61eac3.mp4
> ✨ [FEAT] 내가 작성한 후기글 삭제 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/InfoDetail/InfoCommentTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/SB/InfoSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
closed #182 
- InfoDetailVC를 코드베이스로 짰었는데, 하단 텍스팅영역을 개발하기에 스토리보드베이스가 더 편리할 것 같아서 스토리보드베이스로 변경하였습니다!
- 그리고 질문 채팅 UI에서도 생겼던 텍스팅영역의 자잘한 버그들을 같이 수정했습니다! (원래는 댓글남기고 바로 placeholder가 뜨는게 아니라 빈 textView를 띄웠었는데 에타에 직접 댓글달아서 확인한 결과 placeholder가 뜨길래 그렇게 UI를 수정했음!)
- 정보글에 댓글을 남길 수 있도록 하단 텍스팅 영역을 추가하였고, 전송 버튼을 통해 댓글을 남길 수 있는 기능을 구현했습니다.
- 전체 구현영상 gif
- 원글 작성자가 댓글 남긴 경우
- 키보드 올라왔을 때
> ✨ [FEAT] 과방 정보글 UI 하단 텍스팅 영역, 댓글 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/BaseQuestionTVC.swift
closed #187 
- BaseQuetionTVC 좋아요 아이콘을 diamond에서 heart로 변경했습니다! (*디자인 수정)
- BaseQuestionTVC 파일 한개 좋아요 아이콘 변경하고 레이아웃 조금 다시 손봐줬더니 무려 4개의 UI가 동시에 업데이트됐답니다 짝짝짝 🤗🤗🤗
> 🔨 [FIX] 과방탭 재사용셀 BaseQuestionTVC 좋아요 아이콘 일괄 변경

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomQuestionTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomQuestionTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/BaseQuestionTVC.swift
closed #189
- BaseQuestionTVC에 heartFill 관련 코드를 추가했습니다
- 과방 피드에서 내가 좋아요한 글에 대해서 좋아요 표시되는 기능을 추가했습니다!
- 질문 채팅 UI에서 좋아요 아이콘을 다이아몬드에서 하트로 변경했습니다.
- 과방탭 좋아요관련 수정사항 모두 반영 완료우!
> ✅ [Chore] 과방탭 좋아요 관련 UI 수정사항 반영

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ReviewAPI.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewEditData.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewPostRegisterData.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
closed #183
- 후기글 수정 기능을 구현했습니다.
- 후기 상세뷰에서 후기 작성 뷰로 화면 전환 시 데이터를 전달하여 이전에 작성한 내용이 해당 `textView`에 보이도록 했습니다.
- 후기 작성 상황과 달리 수정 시에는 뷰가 그려질 때 이미 `textView`에 `text`가 있기 때문에 기존 `textViewDidChange()` 에 있던 조건문 코드를 밖으로 빼서 함수화 시키고, `viewWillAppear()`와 `textViewDidChange()`에서 호출하였습니다. 
- 또한 `placeholder` 값을 텍스트로 인식하지 않도록 하기 위해 완료 버튼 활성화 코드를 변경하였습니다.
- x버튼 클릭 시 나타나는 알럿 메시지를 분기처리해주었습니다. 
**클라에서 더미 관리 SSAP POSSIBLE**
- 수정 플로우
https://user-images.githubusercontent.com/63277563/154719532-95839c09-d4ee-4b83-a2f8-18aef0826b92.mp4
- 후기글 수정 상황에서 x버튼 클릭 시
https://user-images.githubusercontent.com/63277563/154721008-6178ecad-ee86-4850-946c-224c836e9466.mp4
> ✨ [FEAT] 내가 작성한 후기글 수정 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift
closed #192 
- 정보글 조회시 하얀 백 로딩뷰 추가
- 첫 진입시에만 데이터가 로딩되기 전 하얀 백 로딩뷰를 추가했습니다! (이유는 뷰가 단색이 아니고 윗면이 흰색, 아랫면(댓글부)이 회색이어서 데이터가 들어오기 전 뷰가 예뻐보이지 않아서 추가했습니돠)
> ✅ [CHORE] 정보글 조회시 하얀 백 로딩뷰 추가 (#192)

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewDetailSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/HalfModalPresentationController.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
closed #197
- 후기탭의 QA를 반영했습니다.
- `HalfModalView`의 블러 효과를 빼고 검정색 반투명 뷰를 깔아주었습니다.
- 좋아요 Label 설정을 수정하였습니다.(컬러, 폰트 굵기) 
\+ 후기 상세 뷰 하단 네비에 날짜 설정 추가하였습니다.
https://user-images.githubusercontent.com/63277563/154914589-577ca152-4e49-4d5b-907b-2af5778de7e3.mp4
> ✅ [CHORE] 후기탭 UI 관련 QA 사항 반영

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/InfoDetail/InfoCommentHeaderTVC.swift
closed #204
- 댓글이 0개일 때 하단 여백을 8px로 설정해주었습니다.
- 댓글이 있는 경우에는 하단에 CommentTVC가 16px의 간격을 두고 배치되기 때문에 이 경우에는 하단 여백을 0으로 분기처리해주었습니다.
- 댓글 0개일 때
- 댓글이 있을 때
> 🔨 [FIX] 과방 정보상세글 댓글 0개일 때 하단 간격 수정

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Classroom/Common/EditPostCommentModel.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Classroom/Common/EditPostQuestionModel.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomCommentTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift
closed #211
- 과방탭 Network 코드 변수, 모델 네이밍 수정이 있었습니다!
- 답변 수정기능을 구현했습니다~! 
- 수정시에는 `isCommentEdited` 변수의 상태를 true로 설정하고, 수정된 indexPath를 `editedCommentIndexPath` 변수에 저장해주어서 `isCommentEdited`가 true이면 전체 tableView를 reload해주지 않고 해당 indexPath의 row만 reload를 해주어 수정되는 느낌을 강조해주었습니다!
> ✨ [FEAT] 질문글 답변 스레드 수정 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/Singleton/MajorInfo.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/HalfModalVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/EntireQuestionListVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainLinkTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Xib/FilterVC.swift
closed #212
- 후기 메인 뷰 필터 기능을 구현했습니다.
- `FilterVC`가 닫힐때 호출되는 setStatus(data: Bool) 함수에서 
싱글톤에 저장해놓은 배열을 이용해 각 상황에 맞게 태그 배열이 서버에 요청되도록 처리해주었습니다.
- 다른 학과 페이지로 이동 시 필터가 초기화 기능을 구현해주기 위해 학과선택 바텀시트인 `HalfModalVC`에서 
필터관련 delegate 처리를 해주었습니다.
- 구동영상은 용량문제로 슬랙에서 확인해주시면 감사하겠습니다!
> ✨ [FEAT] 후기 메인 뷰 필터 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/Singleton/MajorInfo.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/QnAType.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/HalfModalVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/PublicService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/EntireQuestionListVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainLinkTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Xib/FilterVC.swift
closed #215 
- 좋아요 Service moyaTarget case명 수정 
- 질문글 내에서 질문(원글), 답변(댓글) 상태 분기처리를 위해 QnAType(enum) 추가
- 질문글에는 ,, 아주 신기한 전설이 있었으니 ,, 질문 스레드의 흰색 박스는 사실 질문원글, 질문자 댓글로 분리되어 보이지만 같은 셀을 사용한답니다~~ 
- 댓글일 경우 titleLabel에 text가 없어서 sizeToFit을 통해 댓글 부분은 민트색 타이틀 글씨가 안보이게 되는 구런 눈속임을 갖구 있는데요,, 그래서 요 분기처리를 cellForRowAt의 questionCell 내에서 indexPath가 0일경우 아닐경우로 분기처리를 해주고 있습니다!
- 근데 그  if-else문 안에서 또 alert함수를 코드로 if-else 마다 써줘야 하는 문제가 발생해서 중복되는 alert 생성 부분을 함수로 빼게 되었고 alert 코드 내에서 딕셔너리를 이용해서 QnAType에 따른 alertMsg를 짝으로 지어주었습니다. (사실은 같은 셀의 더보기 버튼의 삭제버튼을 누른거지만 질문 원글 삭제일 경우와 질문 댓글일 경우 alertMsg도 다르게 떠야할 것 같아서 이 부분을 분기처리 해주었습니다!)
- 그래서 현재 질문 원글 삭제 부분만 기능을 구현했구요! 질문 댓글 삭제 부분은 다른 API를 이용해야하기에 그 부분을 nil로 설정해둔 상태입니다! (TODO참고 🤗)
- 앗! 그리고 제 코드가 넘 길어가지고 `/// 주석`으로 분기처리마다 설명을 간략하게 달아놓아서 주석 추가 코드가 많으니 깃에서 보기 힘드시더라도 양해 부탁해여 …
> ✨ [FEAT] 과방탭 (1:1, 전체) 질문 원글 삭제 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
closed #218
- 과방 질문글 댓글 삭제기능 구현완료했습니다!
- 기본 tableView 함수 내에서 삭제가 이뤄지는게 아니다보니 tv.deleteRows 함수를 호출해준 후 indexPath가 업데이트되지 않는 상황(삭제 후 0 2 3 4 --> deleteRows호출을 통해 UI만 업데이트되어 indexPath에 공백이 생기는)이 생겨서  indexPath update 코드를 작성해주었습니다!
> ✨ [FEAT] 과방 질문 댓글 삭제 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
closed #222
- 사용자 분기처리를 통해 `userID`와 특정 댓글의 `wirterID`가 같을 경우에 `삭제` 권한을, 다를 경우엔 `신고` 권한을 부여했습니다.
- 과방 정보글 댓글 삭제 기능을 구현했습니다.
- 특정 cell만 삭제하는 모션이 자연스럽지 않고, 댓글 개수도 같이 업데이트되어야하기 때문에 정보글 상세조회 API를 재호출해주었습니다.
**📌 풀리퀘 머지가 되지 않아 전 브랜치에서 따서 작업한 브랜치이기 때문에 커밋 기록이 남아있습니다! `이슈번호 #222` 커밋만 봐주세용!!
[댓글 삭제]
> ✨ [FEAT] 과방 정보글 댓글 삭제 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageSettingAPI.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageSetting/GetLatestVersionResponseModel.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageSettingService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/Cell/SettingTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/Cell/SettingTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/Cell/SettingVersionTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/Cell/SettingVersionTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/SB/SettingAppInfoVC.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/SB/SettingVC.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingAppInfoVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingVC.swift
closed #168 
* 마이페이지_설정~앱정보 플로우 구현
* 인앱/외부 브라우저 연결 구현 (서비스 이용규칙 제외)
* 구현 안 된 뷰들은 이슈 파 뒀고, 구현되는 대로 설정 뷰랑 연결 예정!!
* 탈퇴/로그아웃 같은 큼지막한 기능/네트워킹 코드는 따로 이슈 생성해 작업 예정(코드리뷰 하기 싫은 PR 생성 방지 차원 ..)
* 최신버전받기 (간단한API연결이라) 이건 네트워킹 코드 작성함!
* 설정 부분 테이블뷰 동적/정적 뭘 쓸지 고민을 많이 했는데... 정적 테이블뷰는 뷰 > 컨테이너뷰 > 정적 테이블뷰 이렇게 관리해야 돼서 좀 별로였음. 걍 동적 테이블뷰 썼어욤!
* 단순한 UI 작업 위주라 코드가 길고 딱히 중요한 부분은 없습니다..
https://user-images.githubusercontent.com/43312096/155894541-4f36f213-82de-468a-9045-f14157287475.MP4
> ✨ [FEAT] 마이페이지 설정 뷰/플로우 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
closed #246
- 후기 수정 시 학과 변경 버튼을 누를 수 없도록 비활성화 처리하였습니다.
- 제2전공 미진입 여부 판단해줄때 isPosting 변수 활용해서 같이 판단해주었습니다.
- 후기글 작성 시
https://user-images.githubusercontent.com/63277563/156213857-9887f1b2-bf30-4ce9-9730-47f1ba03b12f.mp4
- 후기글 수정 시
https://user-images.githubusercontent.com/63277563/156213875-93ab8bab-04c5-47cc-babd-a07192c1b5a7.mp4
> ✅ [CHORE] 후기 수정 시 학과 변경 버튼 비활성화

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
closed #241
- 선배 페이지 네비바 타이틀을 해당 선배의 닉네임으로 적용했습니다.
- 궁금한 것이 있는데.. `didSet`에서 `userInfo.nickname`을 넣으면 데이터가 안들어오는 이유가 lifecycle 관련 문제일까여...?
- 구동영상
https://user-images.githubusercontent.com/63277563/156206448-1b7b5642-8523-48bf-974a-b2cc19cd1752.mp4
> ✨ [FEAT] 선배 페이지 네비바 타이틀 선배 닉네임으로 적용

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
closed #225
* 로그인 뷰에서 이메일 유효성 검사 로직을 수정하였습니다! 이제 이메일 필드에 아무것도 없을 땐 빨간색 안내 문구 안 뜸!
없
https://user-images.githubusercontent.com/43312096/156393714-156d3d93-59fc-4386-b72b-12be2b73ea29.mov
> 🔨 Fix: 이메일 유효성 검사 로직 수정 (#225)

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomCommentTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomCommentTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomQuestionTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomQuestionTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
closed #255
- 삭제된 답변일 경우를 고려해 채팅 말풍선들의 최소높이를 수정했습니다. -> `120`
- 채팅 스레드를 삭제할 때 해당 셀이 사라지고 fade되는 애니메이션을 구현했었는데, 셀과 데이터가 아예 사라지는 것이 아니라 (삭제된 답변입니다.) 라고 남아있어야 해서 해당 코드를 지우고, 삭제 시 질문상세get API를 호출해주었습니다.
- 셀마다 isDeleted상태를 받아서 삭제된 답변일 경우 닉네임, 전공정보, 점3개버튼, 좋아요버튼, 작성일을 숨겨주었습니다.
- view의 로직이 tableView로 이루어져 있고, 셀들이 재사용되기 때문에 if-else문을 사용하여 재사용 문제가 없게끔 예외 처리를 해주었습니다.
> 🔨 [FIX] 질문 채팅 스레드 삭제 로직 수정

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/SB/MypageMyReviewVC.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/SB/MypageUserVC.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
closed #256
- 과방 탭의 선배 개인페이지 학과 후기 UI를 구성하였습니다.
- 선배 개인페이지에서 최신순, 좋아요순 정렬을 바꾸었을때 서버통신 과정이 보이도록
loading indicator를 추가해주었습니다.
- 선배 개인페이지 학과 후기 버튼을 누르면 학과 리스트 뷰로 이동하도록 화면전환을 구현하였습니다.
- 학과 후기 버튼 클릭 시 정빈이가 마이페이지 학과 후기 뷰 구성 시 만들어놓았던 `MypageMyReviewVC`에서 
userID로 분기처리를 해서 해당 선배가 쓴 글이 보일 수 있도록 구현하였습니다.
- 좋아요 클릭 시 
https://user-images.githubusercontent.com/63277563/156878548-2ef49771-9484-4d33-aec2-a92e93658737.mp4
- reviewList.isEmpty일 경우 emptyView가 보이고, scroll이 불가하도록 구현
https://user-images.githubusercontent.com/63277563/156821537-c56a9a17-6d5b-4ea2-ac33-33909360f4a0.mp4
**+** 학과 후기 버튼 터치영역 수정
> ✨ [FEAT] 선배 개인페이지 학과 후기 UI 구성

- NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIViewController+.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomCommentEditTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomQuestionEditTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/SB/QuestionChatSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC+TV.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/SB/MypageMyReviewVC.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/SB/MypageUserVC.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC+TV.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC+TV.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/TabBar/VC/NadoSunbaeTBC.swift
closed #258 
1. 앱잼 당시 채팅 스레드에서 send 버튼을 누를 때 버튼에도 탭 제스처가 적용되는 문제가 발생해서 채팅을 보낼 때 키보드가 내려가는 현상이 있었습니다.
2. 그래서 채팅 스레드 뷰에서 `hideKeyboardWhenTappedAround()`함수를 사용하지 않고, 드래그 시에만 키보드가 내려가도록 구현했었습니다.
3. 그런데 QA과정을 거치면서 카톡과 비슷하게 키보드 인터랙션이 되는 것이 유저 입장에서 편할 것 같다는 생각이 들어서 드래그 함수를 제거하고 `hideKeyboardWhenTappedAround()`함수를 써보자는 생각이 들었습니다.
4. 그런데 이 함수를 쓰려면 채팅 스레드 내에서 '전송' 버튼을 누를 때는 키보드가 내려가지 않고 전송 버튼이 눌려야 하므로 -> tap 되는 대상이 `UIButton`일 때는 탭 제스처가 동작하지 않도록 구현하는 방법이 필요했습니다. 
`    ==>  tap Delegate 대리자를 위임해서 gestureRecognizerDelegate함수가 호출될 때 그 호출하는 대상이 UIButton이면 제스처를 동작시키지 않는 구현원리가 필요했습니다.`
5. 따라서....!!!!! `UIViewController+` 에 위치했던 `hideKeyboardWhenTappedAround()` 함수를 저희가 공통적으로 사용하는 `BaseVC()` 내로 옮기고, 대리자를 위임해주었습니다 :)
-  채팅뷰 하단 텍스트영역 뒤로가기하고 재진입시 위로 올라오는 현상 해결
- 키보드 영역만큼 스크롤이 안되는 현상 해결 (바닥부분) -> 뷰가 더 늘어나게 수정 …
> 🔨 [FIX] 과방 질문 채팅 스레드뷰 QA 반영

- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoAlertVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/NadoAlertVC.xib
#267 
* NadoAlert With SingleBtn 만들었습니다
* with TextField는 좀이따.. ㅎㅎ 일단 은주 언니 급하게 써야해서 먼저 올림!!
* 우선 기본적으로 `showNadoAlert` 함수를 쓸 때 원래 type 파라미터가 없었기 때문에... 분기처리를 위해 새로 만들었고, optional로 만들어서 기존에 있던 애들은 기본적으로 `withDoubleBtn`으로 적용됨니다!!
* 은주언니가 SingleBtn 쓰고 싶을 때에는 꼭 `type: .singleBtn` 지정해 줘야 함!!
```
guard let alert = Bundle.main.loadNibNamed(NadoAlertVC.className, owner: self, options: nil)?.first as? NadoAlertVC else { return }
alert.confirmBtn.press {
self.requestSignOut()
}
alert.showNadoAlert(vc: self, message: "로그아웃할래?(미정)", confirmBtnTitle: "네", cancelBtnTitle: "", type: .withSingleBtn)
```
* SingleBtn에는 cancelBtn이 없기 때문에 거기에 press 후 코드 추가하거나, cancelBtnTitle에 파라미터 넣어줘도 안보임! 걍 cancelBtnTitle에는 빈 String이나 아무거나 넣어 주시면 됨ㄴㅣ다...
https://user-images.githubusercontent.com/43312096/156915223-9ee0e218 …
> ✨ [FEAT] NadoAlert case 만들기

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
closed #270
- infoQuestionListTV에 옵저버를 추가했습니다.
- 지긋지긋한 tableView dynamic height.. 종결냈다 ..
- 이 옵저버 하나면 tableView size값이 변경될 때(스크롤 시 셀 재사용과 함께 tableView height가 늘어나야 할 때) 체크해서 tableView height를 업데이트할 수 있어서 estimatedHeight가 정확하지 않아도 서버통신 완료 후 받아온 데이터 개수만큼 문제없이 fit하게 tableView height 만들 수 있음!
<버그 있었던 사진>
<해결 후 사진>
> 🔨 [FIX] 정보 메인뷰 마지막 스레드 길이 버그 수정

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Sign/ResendSignUpMailResponseModel.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Sign/SignUpDataModel.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/SignService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/SB/MailCompleteVC.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/MailCompleteVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/VC/ResetPWVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpMajorInfoVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/VC/SignUpUserInfoVC.swift
closed #277
* 회원가입 후 메일 인증 뷰 구현
* 회원가입 후 메일 재전송 구현
* 로그인 시 메일인증 안 된 유저면 로그인 막고, 재전송 가능하도록 구현
* 기존 ResetPWCompleteVC를 MailCompleteVC로 변경하면서 폴더도 옮기고 싶었는데 ㅎㅎ 컨플릭트 두려워서 우선 냅뒀어요..릴리즈 후 고칠것......
* 회원가입 후 메일 뷰
https://user-images.githubusercontent.com/43312096/156933492-e93fc1a9-5e22-4bd0-af42-eb6da868a704.mov
* 로그인 시 메일인증 안 된 유저 처리
https://user-images.githubusercontent.com/43312096/156933515-5d061466-2f12-460a-a851-093796eb7811.mov
> ✨ [FEAT] 회원가입 메일 인증 플로우

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/NSLayoutConstraint+.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoHorizonContainerViews.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoSegmentView.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/NadoHorizonContainerViews.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyPostListVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypagePostListVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/VC/SignUpUserInfoVC.swift
closed #272
- NadoHorizonContainerView는 추후 몇개가 되든 상관없게끔 확장가능성을 열어두어 리펙토링했습니다. (디폴트는 2개입니다.)
- NadoSegmentView내 btn을 3개로 확장했습니다. (그에 따른 네이밍도 수정 --> first, second, third)
- NadoHorizonContainerView의 viewWidth의 Multiplier를 containerCount만큼 곱해주게되면, stackView의 너비도 해당 너비만큼 커지므로, stackView에 들어갈 수 있는 컨테이너의 개수가 해당 갯수만큼 늘어나게 됩니다.
- 어떻게 확장해서 사용하느냐. 예를 들어 3개의 컨테이너를 사용하고 싶다면, 디폴트인 2개 container는 IBOutlet으로 연결되어있으나 한개 container는 코드로 심어주어야합니다! -> 요건 좋아요목록 구현시 코드로 보여드리겠습니다!
[NadoSegmentView 3개 사용 시]
> ♻️ [REFACTOR] NadoHorizonContainerView, NadoSegmentView 재사용 컴포넌트 확장

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/SB/SignInSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Support/AppDelegate.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Support/Assets.xcassets/logoLogin.imageset/Contents.json
closed #278
- 스플래시 화면을 구성했습니다.
- General에 LaunchScreen File을 디폴트 `LaunchScreen`에서 `SignInSB`로 변경했습니다.
- 스크럼때 스플래시 지속시간 2초로 픽스되어서 데이터 로딩시간까지 2초정도로 보이도록 
appDelegate에 지연시간을 1초로 해두었습니다.
- 자동로그인 API 호출 부분에 loading Indicator설정 코드를 지워 자동로그인 통신 시간까지 스플래시 처럼 보이도록 하였습니다.
https://user-images.githubusercontent.com/63277563/156994852-24d83b42-5917-4a48-9cbc-75ad29d2465a.mp4
> ✅ [CHORE] 스플래시 화면 적용

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/Identifiers.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/MypageLikePostType.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageLikePostDataModel.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageLikeReviewDataModel.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageService.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/BaseQuestionTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/EntireQuestionListVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/SB/MypageSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageClassroomPostListVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageLikeListSB.storyboard
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageLikeListVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageReviewLikeVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainPostTVC.swift
closed #292 
- 과방 최신순/좋아요 정렬 관련 버그 전면 수정하였습니다~
- 전체에게 질문 전체보기 리스트에서 최신순 > 좋아요 > 최신순 조회하면 조회가 되지 않는 오류 해결
- 전체에게 질문 전체보기 리스트, 과방 정보탭에서 뎁스가 깊어진 후 다시 정보리스트로 돌아왔을 때 정렬 정보를 기억하지 못하는 오류 해결
[전체에게 질문 전체보기 리스트]
https://user-images.githubusercontent.com/63224278/157109007-0c55c24e-816e-4c63-9de9-cd142ddd1ef3.mp4
https://user-images.githubusercontent.com/63224278/157109090-e8a473f4-a1ea-4df1-bd78-46b5502c2939.mp4
[과방 정보탭]
https://user-images.githubusercontent.com/63224278/157109144-4ddaa60b-0189-45e8-8d03-7e1e8f8036cf.mp4
> 🔨 [FIX] 과방 최신순/좋아요 정렬 관련 버그 전면 수정

- NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Protocol/SendBlockedInfoDelegate.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomCommentTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomCommentTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomQuestionTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomQuestionTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/InfoDetail/InfoCommentTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/InfoDetail/InfoCommentTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/InfoDetail/InfoQuestionTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/InfoDetail/InfoQuestionTVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/EntireQuestionListVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift
closed #305
- 닉네임, 프로필이미지 위에 버튼을 얹어주었습니다.
- 과방탭 유저의 프로필 이미지, 닉네임을 클릭했을 때 유저의 마이페이지로 이동하는 기능 구현했습니다.
- 원글유저가 차단되었을 시에는 pop 처리를 통해 글을 빠져나가도록 구현했습니다!
- 정보글 UI QA사항, EntireQuestionList > 질문스레드 이동시 하단탭바 오류 버그도 같이 수정했습니다!
[내 프로필로 이동]
https://user-images.githubusercontent.com/63224278/157325088-05add2c0-afef-43ff-a794-b9cb3a7cbd2c.mp4
[선배 마이페이지로 이동 후 원글 유저 차단]
https://user-images.githubusercontent.com/63224278/157325095-a30ce067-7e06-40a3-b779-7c3b3618189c.mp4
[선배 마이페이지로 이동 후 원글 유저가 아닌 타인 차단]
https://user-images.githubusercontent.com/63224278/157325371-030e8bbb-6f40-4447-801f-6067b4992360.mp4
> ✨ [FEAT] 과방탭 유저의 프로필 이미지, 닉네임을 클릭했을 때 유저의 마이페이지로 이동하는 기능 구현

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift
closed #322
- 옵저버를 다시 도입해 사이즈가 변경될 때마다 테이블뷰 사이즈를 변경해주었습니다!
- 글이 3개일 때 탭바에 파뭍혀.. 스크롤뷰가 컨텐츠뷰 영역을 못잡아서 스크롤도 안되구 정적인 뷰로 그려지는 문제가 있어서 게시글 카운트 3일 경우에 스크롤뷰 인셋을 조정해주었습니다.
카톡으루 첨부!
> 🔨 [FIX] 과방 메인 전체에게 질문 TableView Height 버그 해결

- NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/NadoAlertVC.xib
- NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/InfoDetail/InfoQuestionTVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
closed #317 
- 나도알럿 내 나도선배버튼 폰트 오류 해결 -> button의 상태를 default로 지정!
- 과방 정보글 좋아요 UI 라벨 컬러 수정
- requestErr떴을 때 message라벨에 띄우고 pop코드 심으려다가.. 찐 네트워크 오류일 때가 있을 수 있어서 404(삭제된 포스트를 조회했을 경우)에만 해당 기능을 추가해주었습니다! --> 따라서 네트워크 코드도 좀 바뀜!
- 알림탭에서 삭제된 게시글의 알림을 누를 경우 오류 해결
https://user-images.githubusercontent.com/63224278/157438579-e5cf4530-8619-48df-8016-9bbf948fb478.mp4
> 🔨 [FIX] 알림탭에서 삭제된 게시글의 알림을 누를 경우 오류 해결

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC+TV.swift
closed #332
* 알림 탭의 tableView를 1 section 1 row로 구현했는데... 알림 클릭 시 postID 접근할 때 indexPath.row로 접근하던 코드들이 있어서 "작성한 정보글", "답글을 작성한 정보글" 이 엉뚱한 뷰로 이동하는 경우가 있었음. 해결해쓰요
정상적으로 동작
> 🔨 [FIX] 알림탭에서 글로 이동 시 정확한 글로 이동하지 않는 문제 수정

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Support/SceneDelegate.swift
closed #339
- 온보딩 전에 스플래시 뜨지 않는 문제를 해결했습니다.
- 무조건 root뷰컨을 AutoSignInVC(스플래시)로 해주었습니다. 스플래시 이후에 온보딩 판단을해서 어떤 화면으로 전환해줄지 분기처리하여 문제를 해결했습니다.
> 🔨 [FIX] 온보딩 전에 스플래시 뜨지 않는 문제 해결

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
closed #351
- 후기글 수정 시에도 이전 작성 글의 글자수가 표시되도록 수정하였습니다.
- 기존 글자수 카운트 코드를 함수화하여 `viewWillAppear()`에서 한번 더 호출해주었습니다.
https://user-images.githubusercontent.com/63277563/157709585-9863921f-bc9f-4bcb-8793-e62c325c84a8.mp4
> 🔨 [FIX] 후기글 수정 시 이전 작성 글 글자수 표시되지 않는 문제 해결

- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ResetPW/SB/MailCompleteVC.storyboard
closed #362
* 비번찾기/횐가입 후 메일전송완료 뷰 배경색 수정
* 재전송 버튼 좌우 간격 수정
> 🔨 [FIX] 비밀번호 찾기 메일 전송 화면 이미지 수정

- NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/PermissionType.swift
- NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
closed #365 
- 원래 후기 부적절 유저의 경우 첫 진입시에만 부적절 후기 관련 문구가 뜨고, 그 이후부터는 기능 접근시에 후기 미작성자와 동일한 알럿을 띄우는 거였는데,, 갑자기 바뀌었다고 합니다.
- 그래서 firstInappropriate 케이스를 추가해서 처음과 그 이후를 구분해주었습니다!
카톡으루 첨부!
> 🔨 [FIX] 후기 부적절자 관련 알럿 메시지 수정
