NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIFont+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/cls.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/xib.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/TabBar/VC/NadoSunbaeTBC.swift
closed #3 
- 제플린에서 보니 style guide에 나와있는 폰트 사이즈만 적용되는게 아니어서 폰트 사이즈를 가변적으로 조정하여 사용할 수 있게끔 함수화하였습니다.
- 적용 예시) `UIFont.PretendardM(size: 12.0)`
=> ✅ [CHORE] UIFont Extension 수정 및 적용

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIFont+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoSunbaeBtn.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/cls.swift
closed #6 
나도선배 Style UIButton Component Custom Class 생성하였습니다.
**[적용 방법]**
1. button을 스토리보드에서 생성하든, 코드에서 생성하든 커스텀 클래스를 `NadoSunbaeBtn` 으로 설정해주세요.
2. 해당 버튼의 IBOutlet을 연결하여 isActivated 상태를 정의해주세요.
3. isActivated(활성 상태)에 따른 title text 변경은 if문/switch문을 통해 지정 가능합니다! :)
```
// 해당 버튼의 default 상태값 정의
nadoBtn.isActivated = true
// switch구문을 통한 상태별 titleText 정의 하하하 print문은 무시해주세여~~
switch nadoBtn.isActivated {
case true:
print("true")
nadoBtn.setTitle("하이", for: .normal)
case false:
print("false")
nadoBtn.setTitle("바이", for: .normal)
}
```
=> ✨ [FEAT] 나도선배 Style UIButton Custom Class 생성

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoAlertVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/NadoAlertVC.xib
closed #14 
* NadoAlertVC 구현
* 사용법
```
@IBAction func tapAlertBtn(_ sender: Any) {
guard let alert = Bundle.main.loadNibNamed(NadoAlertVC.className, owner: self, options: nil)?.first as? NadoAlertVC else { return }
alert.confirmBtn.press {
print("화긴버튼누름!")
}
alert.showNadoAlert(vc: self, message: "메시지", confirmBtnTitle: "확인", cancelBtnTitle: "시러")
}
```
* `Bundle.main.loadNibNamed` 이거 쓰는 거 너무 귀찮은데 안 쓰는 법 .. 아시는 분??
* 마지막 커밋에 (#이슈번호) 빼먹었는데 담부터 안 까먹겠습니다!!!
=> ✨ [FEAT] NadoAlert 구현

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpComplete/SB/SignUpCompleteVC.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpComplete/VC/SignUpCompleteVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/VC/SignUpUserInfoVC.swift
closed #25 
* 회원가입 - 완료 UI 구성
* 자동로그인은 회원원가입 관련 api 붙이고 추가할 예정
아헐 이전pr에서 갑자기 녹화 이상하게 됐던 게 내가 TextField를 password 처리해놔서 보안땜에 그런거엿음 ;;;;;;;;;;;;;;;;;;;
https://user-images.githubusercontent.com/43312096/148994934-6167be48-e512-474b-82d7-9cad084d6d72.MP4
=> ✨ [FEAT] 회원가입 - 완료 UI 구성

NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UITableView+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/SB/ClassroomSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/DefaultQuestionChatVC.swift
closed #40 
- 과방탭 1:1 질문하기 뷰 키보드 인터랙션 기능을 구현하였습니다.
- 1:1 질문하기뷰 .. 채팅 끗 ..
- 1:1 질문하기 뷰는 이제 서버통신 하면서 더 기능을 붙여나갈(수정 flow와 userType 분기처리) 예정입니다~!
- 질문자 or 지목받은 선배 답변자의 채팅 UI --> 해당 뷰 내에서 채팅을 보낼 수 있음!
-  <img width="375" alt="ezgif com-gif-maker (2)" src="https://user-images.githubusercontent.com/63224278/149398513-312dda53-7a2b-4299-a425-f9a8e744405d.gif">
- 질문자/지목받은 선배 답변자가 아닌 타인일 경우 --> 해당 뷰에서 채팅을 보낼 수 없음. 열람만 가능함.
- <img width="375" alt="IMG_7038" src="https://user-images.githubusercontent.com/63224278/149396268-e0fb2126-bb13-4744-9030-3c7fe29eade7.PNG">
=> ✨ [FEAT] 채팅 UI 키보드 인터랙션 기능 구현 및 1:1 질문 채팅 UI 구현 완료

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIColor+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIScrollView+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoTextView.swift, NadoSunbae-iOS/NadoSunbae-iOS/Support/Colorsets.xcassets/scrollMint.colorset/Contents.json
closed #42 
- 나도선배 style TextView Custom Class를 생성했습니다.
**<사용방법>**
```
class ClassroomMainVC: UIViewController {
@IBOutlet var textView: NadoTextView! {
didSet {
/// placeholder 텍스트와 함께 didSet으로 초기 style 메서드를 호출해줍니다! 
textView.setDefaultStyle(placeholderText: "질문을 남겨보세요 \n선배들이 답변해 줄 거에요!")
}
}
override func viewDidLoad() {
super.viewDidLoad()
textView.delegate = self
// Do any additional setup after loading the view.
}
}
// UITextViewDelegate는 아쉽게도.. custom class로 분리가 안되더라구여..? 그래서 요 부분부터는 복사해서 사용해주심 됩니다,, text부분만 placeholder랑 통일시켜주세여!
// MARK: - UITextViewDelegate
extension ClassroomMainVC: UITextViewDelegate {
/// textViewDidBeginEditing
func textViewDidBeginEditing(_ textView: UITextView) {
if textView.textColor == .gray2 {
textView.text = nil
textView.textColor = .mainText
}
}
/// …
```
=> ✨ [FEAT] 나도선배 Style TextView Custom Class 생성

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostTVC.xib, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailPostWithImgTVC.xib, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
closed #67
- 작성된 게시글의 길이에 따라 `TVC`가 동적으로 변할 수 있도록 코드 수정했습니다.
- `tableView.automaticDimension` 친구를 사용해주었는데 cell에 준 `inset`값 때문에 
cell이 이상하게 보여서...그냥 `xib`의 UI를 변경해주었습니다^^
(Thanks to 같이 안자고 도와준 지은걸...💜)
**+** 앞 pullRequest 머지 되면 코리 달아주세여.....file changed에 다들어와있네열....
https://user-images.githubusercontent.com/63277563/149857028-b0e1236f-7a8b-4d5a-a454-307b536417e6.mp4
=> 🔨 [FIX] 후기 상세 뷰 contentLabel 길이에 따른 TableViewCell 동적 높이 구현 

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/DefaultQuestionChatVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/QuestionMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/QuestionPersonListVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Support/SceneDelegate.swift
closed #76 
- bundle id 재수정
- 라이브 QA 반영돼서 여러 파일들 수정이 있었고여
- 빌드 1(2)
- 일단 제대로 대응 안되어있는 다크모드는 막아놨습니당~!
=> ✅ [CHORE] testFlight 등록 위한 내부 설정

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UserDefaults+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIEssentials/APIConstants.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ReviewAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIServices/s.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift
closed #81 
- Network폴더 내 APIService 폴더명을 APIManagers로 변경하였습니다.
- Userdefaults+ key value를 업데이트하였습니다.
=> ✅ [CHORE] 서버 통신 기초 세팅

NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
closed #86 
- Userdefaults에 ku5 유저 값들 디폴트로 박아두었습니다-!
=> ✅ [CHORE] Login버튼 클릭시 Userdefaults에 임의 값 지정해두기

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ReviewAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/LikeData.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewPostData.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewPostRegisterData.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/WriterData.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
closed #56 #90
- 후기글 작성 API를 연결했습니다.
변경사항 및 주의 사항 (모듈 설치 등)을 적어주세요.
- 후기글 등록을 POST 서버통신으로 구현했습니다.
- `Model`중 재사용 가능할 것 같은 구조체들은 따로 파일로 빼두었습니다.
=> ✨[FEAT] 후기글 등록 API 연결

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Classroom/QuestionChat/AddCommentData.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/DefaultQuestionChatVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/QuestionMainVC.swift
closed #106 
과방 메인에서 전체 질문 채팅 조회, 채팅 뷰에서 댓글 추가 기능 구현하였습니다!
=> ✨ [FEAT] 과방 메인에서 전체 질문 채팅 조회 화면 연결 및 질문 작성 API 연결

NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Notification/NotificationDataModel.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/SB/NotificationSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC+TV.swift
closed #104
* 알림 탭에서 '질문' 뷰로 이동하는 알림일 때, 1:1 질문인지, 전체 질문인 지 파악하여 처리하는 코드 작성
* 알림 탭 레이아웃 수정
https://user-images.githubusercontent.com/43312096/150410551-5b66a570-2462-4c61-a02b-840a57a4e78c.MP4
=> 🔨 [FIX] 알림 API 수정사항 반영

NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UILabel+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/QuestionType.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoSunbaeNaviBar.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/Chat/ClassroomQuestionTVC.xib, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/BaseQuestionTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/EntireQuestionListTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/QuestionEmptyTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/QuestionFooterTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/QuestionHeaderTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/SB/QuestionChatSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/ClassroomMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/DefaultQuestionChatVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/GroupQuestion/EntireQuestionListVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/PersonalQuestion/QuestionPersonListVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/QuestionMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewWriteSB.storyboard
closed #108 
- !!!
- umm... adjusted 적용해서 12 pro max 대응을 했습니다 (과방 한정)
- 과방탭 write(작성뷰) questionType 분기처리
- NadosunbaeNaviBar 오토레이아웃 수정
- 네비바 shadow 적용
- 전체 질문 리스트 조회 구현 및 채팅뷰 연결
=> ✨ [FEAT] 과방 전체에게 질문 entire list 조회 및 채팅뷰 연결

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoAlertVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoSunbaeBtn.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/CreateClassroomPostModel.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/SB/MypageSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/SB/NotificationSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC.swift
closed #113
* ClassroomAPI 붙이기 및 연결
* NadosunbaeBtn 로드 시에만 isActivated, isEnabled 동기화
* WriteQuestionVC를 띄울 때, answerID는 평소에는 안 건드리고, 1:1 질문 시에만 answerID에 질문받을 사람의 userID를 넣어 주시긔
=> ✨ [FEAT] 과방 글 작성 API 연결

NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/NotificationAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/SB/MypageUserVC.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC+TV.swift
closed 122였는데 ...
* 알림 - 마이페이지 1:1 질문 뷰 연결
=> 🔨 [FIX] 마이페이지, 알림 QA 반영 (#122)

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ReviewAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewHomePageData.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainLinkTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainLinkTVC.xib, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
closed #129
- 학과에 해당하는 URL을 받아오는 API를 연결하였습니다.
- 최초 접속했을때는 유저디폴트의 값을 `majorId`로 받고, 그 이후 리로드 시에는 싱글톤에 저장된 `majorId`로 통신하는 방법을 사용하였습니다.
=> ✨[FEAT] 학과 홈페이지 조회 API 연결

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/Cell/NotificationTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Support/AppDelegate.swift, NadoSunbae-iOS/NadoSunbae-iOS/Support/Info.plist
closed #122 
* 푸시알림이 foreground에서도 보이게 설정하였습니다...
* 진동은 여전히 안됨.. 왠지는 모름. . ㅠㅠ
*
=> 🔨 [FIX] Push 알림 Foreground 설정

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/Struct/QuestionType.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Review/ReviewPostDetailData.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/DefaultQuestionChatVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewDetailSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
closed #143 
- 과방탭 질문 전체보기 좋아요/최신순 필터 오류를 해결하려고 이슈와 브랜치를 팠으나 자동으로 해결되어있는 매직!
- 그래서 은주랑 후기 상세보기 좋아요 구현을 했습니다 !
걍.우리.좀.쩌는듯.
수정.삭제.말고 다붙임.
=> 🔨 [FIX] 과방탭 질문 전체보기 -> 좋아요/최신순 필터 정렬 오류 해결 & 후기 상세뷰 좋아요 기능 구현

NadoSunbae-iOS/NadoSunbae-iOS/Support/AppDelegate.swift
closed #124
- appdelegate 수정
- 디바이스 모드 세로모드로 고정
=> ✅ [CHORE] 디바이스 방향 세로모드로 고정하기

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
- commit message가 적절한지 확인해주세요
closed #145 
해당 pr에서 작업한 내역을 적어주세요.
변경사항 및 주의 사항 (모듈 설치 등)을 적어주세요.
=> ✅ [CHORE] 배경 디폴트 체크 이미지 뜨도록 수정 

NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoSegmentView.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoSunbaeNaviBar.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/QuestionHeaderTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/DefaultQuestionChatVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/EntireQuestionListVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
closed #147 
디자이너분들이 요청한 버튼들에 vibrate를 지정해주었슴!!
=> ✨ [FEAT] 버튼 vibrate 지정하기

NadoSunbae-iOS/NadoSunbae-iOS/Support/AppDelegate.swift
closed #152 
foreground일 때 푸시가 안오는 버그 해결
foreground일 때 푸시가 안오는 버그 해결
=> 🔨 [FIX] foreground일 때 푸시가 안오는 버그 해결

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/Singleton/FilterInfo.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/Singleton/ReviewFilterInfo.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Xib/FilterVC.swift
closed #159
- 기획 수정사항에 따라 필터 UI를 수정했습니다.
- 필터 초기화 기능을 위해 선택완료 버튼이 항상 활성화되도록 UI를 수정하였습니다.
- `Singleton Pattern`을 사용하여 필터 적용이 되었을 때 버튼 클릭 시 이전에 선택한 필터 상태가 보이도록 구현하였습니다.
(싱글톤으로 선언한 배열에 선택된 버튼의 상태 값을 저장하는 방식으로 구현)
- 구동영상
https://user-images.githubusercontent.com/63277563/152998396-67816096-a913-4f76-a104-16723d38ecda.mp4
=> ✅ [CHORE] 기획 수정사항에 따른 필터 UI 수정

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageMyReviewModel.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/SB/MypageMyReviewVC.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyPostListVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyReviewVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainPostTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainPostTVC.xib
closed #166
* 마이페이지 > 학과후기 UI 개발, API 연결, 플로우 다듬기
* BaseVC에 showTabbar(), hideTabbar() 함수 추가함! 사실 기능은 한 줄로 구현이 가능하지만... 먼가 가독성이 별로고 계속 한 줄짜리 코드 추가하는 게 귀찮아서 만들었습니다~
* 학과후기 뿐만 아니라 이전 pr에 올렸던 내가 쓴 글/답글 부분에도 tabbar 안 보이게 수정함! 디자인에 거기는 탭바 없더라고여
* 은주언니 ReviewMainPostTVC에 프로퍼티랑, 함수 추가했는데 그부분 봐주ㅕ용~
=> ✨ [FEAT] 마이페이지 프로필 영역 플로우 개발

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoTextView.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ClassroomAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Classroom/Common/EditPostQuestionModel.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/EntireQuestionListVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC+TV.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyPostListVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC+TV.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC+TV.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
closed #207
- NadoTextView 재사용 컴포넌트에서 초기 상태에 placeholder를 사용하는지, 그렇지 않은지를 분리하기 위해 `isUsePlaceholder` 매개변수를 추가하였습니다.
- 과방 질문 원글 수정 기능을 구현했습니다! (항상 첫번째 채팅글 -> 원 질문글)
=> ✨ [FEAT] 과방 질문상세 채팅 스레드 질문 수정 기능 구현

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewMainPostTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift
closed #226
- 후기 탭 QA사항을 모두 반영했습니다.
- 후기 메인 뷰 태그 셀 간격 조정
- 후기글 수정 시 이전 선택한 이미지가 아닌 디폴트 이미지 체크되는 문제 해결
(이전 선택 이미지에 체크 표시 뜨도록 수정)
- 구동영상
https://user-images.githubusercontent.com/63277563/155889029-c51b4068-cf9c-41f5-acaa-c3b1825c3766.mp4
=> 🔨[FIX] 후기 탭 QA 반영 

NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIViewController+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/PublicAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/PublicService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
closed #240
x
- 정보글 신고기능 구현했습니다!
- 밑 pr이 머지가 안돼서 브랜치를 따서 작업하는 바람에 커밋이 섞여있습니다! `#240`만 봐주세요!
=> ✨ [FEAT] 과방 정보글 신고기능 구현

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionPersonListVC.swift
closed #242 
- 질문가능선배 리스트 받아오는 viewDidLoad로 함수 호출 시점을 변경했습니다!
x
=> 🔨 [FIX] 질문가능선배 리스트 받아오는 getMajorUserList()함수 호출시점 변경

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
closed #252
- 후기글 신고 기능을 구현했습니다.
- 지은걸이 신고 API와 액션시트를 기깔나게 만들어줘서 저는 숟가락만 얹었습니다..복붙만 해써요...
땡스투 지은걸..알러뷰 지은걸..💜
- 최초 신고 경우
https://user-images.githubusercontent.com/63277563/156406421-9750bb2e-d44a-4872-a1c4-d131b9888b7d.mov
- 이미 신고한 글 신고 경우
https://user-images.githubusercontent.com/63277563/156406515-3de609ea-6af9-48fa-bd00-feff5f906910.mov
=> ✨ [FEAT] 후기글 신고 기능 구현

NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIViewController+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC+TV.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageUser/VC/MypageUserVC+TV.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC+TV.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/TabBar/VC/NadoSunbaeTBC.swift
closed #260 
- 알림탭에서 '작성한 정보글, 댓글을 남긴 정보글' 알림의 경우 InfoDetailVC로 이동하는 기능 추가
=> ✅ [CHORE] 알림뷰에서 정보글로 이동하는 기능 구현

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/Cell/TVC/QuestionMain/BaseQuestionTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/Cell/MypagePostListTVC.swift
closed #263
- likeImgView 프로퍼티의 기본 에셋을 heart에서 btn_heart로 변경했습니다
- 왕큰하트가 나왔던 이유 .. ㅋㅋㅋㅋ 는...!! ㅋㅋㅋ 좀 어이없긴한데 해당 프로퍼티의 기본 이미지가 일단 너무 컸고 좋아요 반영하면서 코드짰던 에셋이랑 달라서 생긴 일이었어 
- 마이페이지에서는 setData함수에서 좋아요 반영 관련 코드를 추가안해서 기본 프로퍼티 에셋이 불리고 있었거든ㅋㅋㅋㅋ 그래서 수정해주었습니다!! 별 일이 아니었숨~~
=> 🔨 [FIX] 마이페이지 내가 쓴 글/내가 쓴 답글 엄청나게 큰 하트 버그 수정

NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Sign/SignInDataModel.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/SignService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
closed #284
* 자동로그인 서버 api 새로 만들어준거 붙임(이걸로 액세스토큰 갱신까지 같이할예정)
* 메일인증 안 된 유저 분기처리 수정(아까 회의 때 말한 isEmailVerified == false인 유저 문제 이제 해당없음 고침)
* 이 pr 머지하고 나서부터는 이메일 인증 안 된 유저는 무조건 서버쌤들한테 부탁하기!
=> ✨ [FEAT] 자동로그인 서버 변경사항 대응

NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
ㄴㄴ 긴급pr임
나 이 브랜치 그대로 작업할게여...
함수명 바꾼 게 제대로 반영이 안 되어 있어서 수정했습니다
=> 🔨 [FIX] 함수명 관련 에러 수정

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailGrayTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailGrayTVC.xib, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Cell/TVC/ReviewDetailProfileTVC.xib, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewDetailSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
closed #303
- 후기 상세 뷰 프로필관련 QA와 수정사항을 반영했습니다.
- 내가 쓴 글일 경우 프로필 나오지않도록 수정사항 대응 (하단 여백 높이만큼 빈셀 만들어서 등록)
- 프로필버튼 셀 버튼이 클릭되지 않는 문제가 있어 `ImageView`로 변경했습니다.
- **+** 좋아요버튼 UI 동적 너비 적용
- 내가 쓴 글, 타인이 쓴 글
- 좋아요 버튼 텍스트 길이에 따라 동적너비 적용
=> 🔨 [FIX] 후기 상세 뷰 프로필 관련 QA 및 수정사항 대응

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/Singleton/UserToken.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ClassroomService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/MypageSettingService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/NotificationService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/PublicService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/ReviewService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/SignService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
closed #297
해결이 맞나 싶지만... 
첫 "제대로로그인" 이후 5~6초만 기다리면 그다음부터 자동로그인&온보딩은 정상적으로 동작합니다.....................
* 액세스토큰 갱신 이후 QuestionMainVC 재요청 해결
* MypageAPI getMyInfo accessToken 갱신 처리
* accessToken, refreshToken 싱글톤으로 관리
..
..
https://user-images.githubusercontent.com/43312096/157285281-34343f86-1448-4d29-a214-b2127bab7229.mov
=> 🔨 [FIX] 자동로그인, accessToken 갱신 에러 해결

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/PublicData/Singleton/AppVersion.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/Cell/SettingVersionTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/Setting/VC/SettingAppInfoVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
closed #298 
* 업데이트 확인 알럿창 추가
* AppVersion 관리하는 싱글톤 객체 추가 (이제 앱 업뎃할때마다 여기 코드에서 현재버전만 수정하면댐)
* 설정뷰에서 앱버전 조회하는 코드 제거 -> BaseVC로 이동
* 후기탭 진입 시 최신 버전 판단 함수 호출
..
https://user-images.githubusercontent.com/43312096/157298110-f2a09580-7ef1-46ce-9881-7270b18d48d6.MP4
=> ✨ [FEAT] 업데이트 확인 알럿창 심기

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Global/Extension/UIView+.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/SB/SignInSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/AutoSignInVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Support/AppDelegate.swift
closed #309
- 스플래시에 fade효과를 적용했습니다.
- FadeIn, Out효과를 어디에서나 적용가능하도록 함수를 `UIView+` 파일에 추가했습니다.
- 기존에 디폴트 launchScreen을 `SignInSB`로 적용했던 것을 다시 `LaunchScreen.storyboard`로 변경해서 효과를 주었습니다.
https://user-images.githubusercontent.com/63277563/157311187-68fc02f6-7718-4247-b2b8-5386648baf08.mp4
=> ✨ [FEAT] 스플래시 fade 효과 적용

NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/MajorTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/MajorTVC.xib
closed #315
- 즐겨찾기 버튼과 관련 코드를 삭제했습니다!
x
=> ✅ [CHORE] 학과 리스트 바텀 시트 UI 수정

NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/MoyaTarget/NotificationService.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageReviewLikeVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Notification/VC/NotificationMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift
closed #313
* 액세스토큰 갱신 오류 수정(thanks to @hwangJi-dev)
* 앱 최신 버전 조회 버그 해결 -> 음... 기껏 함수 만들어 놓고 이상한 함수 불러놨더라고여 ㅋ...
정상적으로 동작
=> 🔨 [FIX] 액세스토큰 갱신 시 싱글톤에 잘못 저장하는 버그 수정

NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoAlertVC.swift
closed #319
* NadoAlertwithTextField (탈퇴 시)에, 텍스트필드 상태에 따라 확인 버튼 상태 변경하는 함수를 만들어 적용하였습니다!
* 스샷에서 비번 입력 중일 땐 비번 입력 모드라 녹화가 안됨 ㅠ .ㅠ
https://user-images.githubusercontent.com/43312096/157397732-6c1178d9-f0f3-408b-b963-e09511c918a4.mov
=> 🔨 [FIX] 탈퇴 알럿 QA 대응

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/SB/EditProfileVC.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/ProfileSetting/VC/EditProfileVC.swift
closed #308
* 닉네임 확인 버튼, 제2전공 진입시기 선택/변경 버튼 텍스트 수정
* 중복 체크 완료된 닉네임은 placeholder 말고 text로 넣도록 수정
* 닉네임 확인 버튼 터치 시 키보드 내려가도록 설정
없써용
https://user-images.githubusercontent.com/43312096/157394838-2ec42049-b261-41f3-88ec-c04aff674f12.mov
=> 🔨 [FIX] 프로필 수정 QA 대응

NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignIn/VC/SignInVC.swift
closed #323 
* 비밀번호가 없어도 로그인 버튼이 활성화되는 문제 해결
* 텍스트필드 비우기(X)버튼 눌렀을 때 로그인 버튼이 활성화된 상태로 있는 문제 해결
* 로그인 안내 메시지 통일(서버값으로 안 하고, 변경된 디자인 에러 플로우대로!)
* 없어용
https://user-images.githubusercontent.com/43312096/157431191-b698e761-0b1d-4a95-a66f-cf3334b7d9a9.MP4
=> 🔨 [FIX] 로그인 QA 대응

NadoSunbae-iOS/NadoSunbae-iOS.xcodeproj/project.pbxproj, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SelectMajorModalVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/SB/SignUpUserInfoVC.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpUserInfo/VC/SignUpUserInfoVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Support/Info.plist
closed #328 
* 회원가입 > 기본정보 > 이메일 입력 placeholder가 아닌 text에 "@korea.ac.kr" 넣어두기
* 회원가입 > 기본정보 > 이메일 유효성 검사에 "@korea.ac.kr" 포함되는 조건 추가
* 전공 진입시기 최신순으로, 22-2제외
* 회원가입 > 기본정보 > 비번 입력 시 키보드 올라올 때 뷰 높이 수정
* QA [전체] 글 작성시 작성 요소 한글화 처리
* 비번 입력 시 강력한 암호 안나오게 처리..
https://user-images.githubusercontent.com/43312096/157447281-d1631c91-3e47-4841-a585-e21aef4fc245.MP4
=> 🔨 [FIX] 회원가입 QA 대응

NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Xib/NadoHorizonContainerViews.xib, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageMyAnswerListModel.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIModels/Models/Mypage/MypageMyPostListModel.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/QuestionMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageClassroomPostListVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/LikeList/MypageReviewLikeVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/Cell/MypagePostListTVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/SB/MypagePostListVC.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypagePostList/VC/MypageMyPostListVC.swift
closed #321
- 마이페이지 내가쓴 질문글/질문답글 네트워크 수정사항 대응을 위해 response model을 변경해주었음
- 내가쓴 질문글/질문답글 TVC 통일감을 위해 인셋을 제거해줌
- 마이페이지 내가쓴 질문글/질문답글 네트워크 수정사항 대응
- 좋아요 후기 목록 UI 수정 (스크롤 엄청 길었던 문제) --> 질문, 정보랑 TVC 구조자체가 다르고, dynamic height을 쓰는게 아니다보니 통일감을 주기 위해 코드가 좀 복잡함. scrollview 내에 tableview를 배치했기 때문에 reload시점에 tableview의 높이를 알아야 스크롤영역이 생기기 때문에 양해부탁! 
[좋아요 후기 목록 대응사항]
https://user-images.githubusercontent.com/63224278/157468121-ba81c8f5-2bcd-4346-a3e4-6e787b0b0d9c.mp4
[마이페이지 내가쓴 질문글/질문답글 대응사항]
https://user-images.githubusercontent.com/63224278/157468242-c3f7cd94-8b89-429d-a9dd-ea2fe8c62493.mp4
=> 🔨 [FIX] 마이페이지 내가쓴 질문글/질문답글 네트워크 수정사항 대응, 좋아요 후기 목록 UI 수정

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/SB/InfoSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift
closed #336
- 정보글 키보드관련 스크롤시 키보드가 내려가는 기능을 제거하고, 화면 터치시 키보드가 내려가도록 기능을 변경했습니다.
- 정보글 댓글 작성시 스크롤하면 키보드가 내려가면서 텍스트필드가 지워지는 현상 해결했구 스크롤 인디케이터도 지웠습니다!
- 카톡으로 첨부.
=> 🔨 [FIX] 정보글 댓글 작성시 스크롤하면 키보드가 내려가면서 텍스트필드가 지워지는 현상 해결

NadoSunbae-iOS/NadoSunbae-iOS/Global/Class/BaseVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/PublicAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Info/InfoDetailVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
closed #343 
closed #344 
- reportAPI를 BaseVC로 이동
- 신고 알럿 메시지를 띄워주기 위해 분기처리가 필요했기 때문에 서버와 합의 후 네트워크 코드 status 409 추가
- 삭제된 포스트 조회할 때 알럿 문구 수정
- 중복 신고하는 경우 알럿 문구 수정
[삭제된 포스트 조회할 때 알럿 문구 수정]
[중복 신고하는 경우 알럿 문구 수정]
=> 🔨 [FIX] 포스트 알럿 문구 수정하기

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/SB/ReviewWriteSB.storyboard, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewMainVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewWriteVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/Xib/FilterVC.xib
closed #346
- 글자 수 표시 기능을 구현했습니다.
- `textViewDidChange`에 텍스트 표시 코드를 넣어 `textView`가 바뀔때마다 실시간으로 `label`이 바뀌도록 구현했습니다.
- 카톡으로 확인해주세요~!
=> ✅ [CHORE] 후기 작성 뷰 글자수 세기

NadoSunbae-iOS/NadoSunbae-iOS/Screen/SignUp/SignUpMajorInfo/VC/SignUpMajorInfoVC.swift
closed #350
* 회원가입 제2전공 선택 관련해서 다음 버튼 활성화/비활성화 오류를 수정..했습니데 로직 자체를 수정함
* 미진입일 때 -> 진입시기 선택버튼 회색으로 처리해서 시각적으로도 선택 못하는 것처럼 보이게 수정해씀다
https://user-images.githubusercontent.com/43312096/157705965-83c40d81-1e9b-40c1-8d17-9dd61d0d1c21.MP4
=> 🔨 [FIX] 회원가입 전공 선택 미진입 선택 오류

NadoSunbae-iOS/NadoSunbae-iOS/Global/UIComponent/Class/NadoTextView.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/WriteQuestionVC.swift
closed #349 
- 질문, 정보 작성뷰 textView의 자동완성 기능을 제거했습니다!
https://user-images.githubusercontent.com/63224278/157726735-099cb881-e364-4fd4-aab0-bddccf95825a.mp4
=> 🔨 [FIX] 질문, 정보 작성뷰 textView 자동완성 기능 제거하기

NadoSunbae-iOS/NadoSunbae-iOS/Screen/Review/VC/ReviewDetailVC.swift
closed #356
- 마이페이지 get통신에서 statusCode 200, 204일 때(글 하나도 없는 경우) 데이터 타입이 달라서 생긴 문제여서
서버 분들한테 변경 요청해서 변경했습니다. 
- 그래서 제가 한건 주석 삭제 밖에 없네요 하하ㅏ하
=> 🔨 [FIX] 마이페이지 내가 쓴 후기 마지막 하나 삭제했을 때 바로 반영되지 않는 문제 해결

NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/MypageSettingAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/PublicAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/ReviewAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Network/APIManagers/SignAPI.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Classroom/VC/Question/DefaultQuestionChatVC.swift, NadoSunbae-iOS/NadoSunbae-iOS/Screen/Mypage/MypageMain/VC/MypageMainVC.swift
closed #368
- 로거 정리!
알림탭 뎁스에서 알림 클릭시 알림 메인 리스트로 가지 않는 현상 해결!!
- 카톡으루 첨부!
=> 🔨 [FIX] 알림탭 뎁스에서 알림 클릭시 알림 메인 리스트로 가지 않는 현상
